### ISSUE TITLE
Compatibility issue with MonsterMash mod

### ISSUE THREAD

**Issue by Tishbyte** [Goorakh/ModelSwapperSkins#4] opened 2024-06-03 23:38 UTC
Hi,
Using MonsterMash ([https://thunderstore.io/package/CherryDye/MonsterMash/](https://thunderstore.io/package/CherryDye/MonsterMash/)) with ModelSwapperSkins breaks skin selection and prevents models from showing in the loadout.
I was also planning to post an issue on their page as well, but they don't have a linked GitHub repository.

p.s. love the mod, absolutely cursed,

**Comment by Goorakh** [comment] 2024-06-03 23:44
Hi!

This is a known issue and will be fixed in the next update. When that will be, I don't know (though it is mostly ready at this point), but for now these mods are just incompatible unfortunately. The issue is mostly on ModelSwapperSkins' end though, so you do not need to report this to the MonsterMash dev(s)

Thank you for reaching out :)

**Closed as completed by Goorakh** 2024-06-03 23:44 UTC
